user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;

    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;

    upstream sys-api {
        server lightops-sys-api.lightops:1001;
    }

    upstream cmdb-api {
        server lightops-cmdb-api.lightops:1201;
    }

    upstream ops-api {
        server lightops-ops-api.lightops:1301;
    }

    # server {
    #     listen 80 default_server;
    #     server_name admin-sdwan.xxcig.com;
    #     rewrite ^(.*)$  https://$host$1 permanent;
    # }

    server {
        listen       80 default_server;
        server_name  localhost;

        root /usr/share/nginx/html;
        index index.html index.htm;
        location / {
            if (-d $request_filename){
              rewrite ^/(.*)([^/])$ http://$host/$1$2/ permanent;
              }
            try_files $uri $uri/ /index.html;
        }

        location /api/sys {
            proxy_pass http://sys-api;
        }

        location /api/cmdb {
            proxy_connect_timeout 20s;        # 连接超时时间
            proxy_send_timeout    20s;       # 发送超时时间
            proxy_read_timeout    20s;       # 读取超时时间
            proxy_pass http://cmdb-api;
        }

        location /api/ops {
            proxy_pass http://ops-api;
        }

    }
}