events {
    worker_connections  1024;
}

http {

  upstream cmdb {
      server 82.157.76.7:32001;
  }

  upstream sys {
      server 82.157.76.7:31001;
  }



  server {
      listen       8080;
      server_name  localhost;

      #charset koi8-r;
      #access_log  /var/log/nginx/host.access.log  main;

      root /usr/share/nginx/dist;
      index index.html index.htm;

    #   autoindex on;

      location / {
          if (-d $request_filename){
          rewrite ^/(.*)([^/])$ http://$host/$1$2/ permanent;
      }
          try_files $uri $uri/ /index.html;
      }

      location /api/sys/ {
          proxy_pass http://sys/api/sys/;
      }

      location /api/cmdb/ {
          proxy_pass http://cmdb/api/cmdb/;
      }
    

    error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
  }
}
